language: go

go:
  - 1.15.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - cd litelog && go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - source .codecov.env && bash <(curl -s https://codecov.io/bash)