version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    steps:
      - run: 
          command: export CODECOV_TOKEN="15977ed4-c825-40e5-8809-83dc43d36f66"
      - codecov/upload:
          file: cover.out